#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.example.usercenter.mybatis.entity

# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost


spring:
  application:
    name: usercenter
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner_manage_system
    username: root
    password: 123456
  # redis
  redis:
    port: 6379
    host: localhost
    database: 0

  session:
    timeout: 86400  # session有效时间 (1天)
    store-type: redis  # 从哪里取ssession
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 不开启java class 驼峰属性名 -> 数据表字段下划线 的映射
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑删除值 (默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值 (默认为0)

# knife4j
knife4j:
  enableAggregation: true
  cloud:
    enable: true
